# https://taskfile.dev
version: "3"
tasks:
  run: docker run --rm -it --env ENV1="env1-test-in-run-cmd" hello sh

  # docker build --help
  build: docker build --tag hello --no-cache --progress plain .
  build-with-arg: |
    docker build --tag hello --no-cache --progress plain --build-arg ARG1=arg1test-in-build-cmd .
