# https://taskfile.dev
version: "3"
includes:
  # fly related tasks
  fly-io:
    taskfile: ./Taskfile-flyio.yml
    aliases: [f, fly]
    optional: true

tasks:
  gh: https://github.com/cao7113/dailyops/tree/main/flyio/flynet-test

  ## fly
  fly-sh: fly ssh console
  fly-up: fly scale count 1 --yes
  fly-down: fly scale count 0 --yes
  fly-deploy: fly deploy --image ghcr.io/cao7113/flyio-try
  ## dns dig https://fly.io/docs/networking/private-networking/#fly-io-internal-dns
  fly-apps: dig _apps.internal txt

  ## Docker
  dk-build: docker build -t flynet-test .
  dk-run: 
    deps: [dk-build]
    cmds:
    - docker run --name flynet-test --rm -it -e PORT=7777 -p 6666:7777 flynet-test
