# https://taskfile.dev
version: "3"
vars:
  ub_base: "ubuntu:22.04"
  bb_base: "busybox"
tasks:
  hi:
    cmds:
      - docker run --rm -p 80:80 docker/getting-started

  ub: docker run --rm -it {{.ub_base}}

  pl-bb: docker pull {{.ub_base}}
  pl-ub: docker pull {{.bb_base}}

  ## Tools
  # https://hub.docker.com/r/curlimages/curl
  get-curl-img: |
    docker pull docker.linkos.org/curlimages/curl:8.8.0
    docker tag docker.linkos.org/curlimages/curl:8.8.0 curlimages/curl:8.8.0
    # docker rmi docker.linkos.org/curlimages/curl:8.8.0
    # docker run --rm curlimages/curl:8.8.0 -L -v https://curl.se

  rand:
    cmds:
      - |
        docker run -d ubuntu:22.04 \
        bash -c "shuf -i 1-10000 -n 1 -o /data.txt && tail -f /dev/null"

  version:
    cmds:
      # docker --version
      - docker version
      # - docker info
