# fly.toml app configuration file generated for flyup-test on 2024-07-15T18:14:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flyup-test'
primary_region = 'nrt'

[build]

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
