# An inventory in YAML format becomes a sensible option as the number of managed nodes increases.
# Ensure that group names are meaningful and unique. Group names are also case sensitive.

# Automatically accept host SSH keys
all:
  vars:
    # Specify the Python interpreter
    # ansible_python_interpreter=/usr/bin/python3
    # Automatically accept host SSH keys
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

orb_hosts:
  hosts:
    # the key is host unique name
    # or use format: "a1@orb:"
    a1:
      ansible_host: a1@orb
    # a2:
    #   ansible_host: a2@orb
    ##
    ## below formats NOT work! orb自带的ssh-server是在宿主机上运行的，并非在真正的vm中运行!!!
    ## 还是遵循orb的规则，ref: https://docs.orbstack.dev/machines/ssh#ansible
    # a1:
    #   ansible_host: a1.orb.local
    # a2:
    #   # ansible_user: default
    #   ansible_host: localhost
    #   ansible_port: 32222
    #   ansible_ssh_private_key_file: ~/.orbstack/ssh/id_ed25519

  # vars:
  #   # ansible_user: default
  #   ansible_host: localhost
  #   ## connection info from `orb ssh`
  #   # Host: localhost
  #   # Port: 32222
  #   # User: default
  #   # Private key: ~/.orbstack/ssh/id_ed25519

# mac_hosts:
#   hosts:
#     # local mac host connect OK if ssh-daemon opened!
#     m1:
#       ansible_host: localhost
#       # ansible_port: 22
#       # ansible_ssh_private_key_file: ~/.ssh/id_rsa
#       ansible_python_interpreter: /usr/bin/python3

# metagroup that organizes multiple groups in your inventory
all_hosts:
  children:
    orb_hosts:
    # mac_hosts:
