# https://taskfile.dev/usage/
version: "3"
vars:
  FLY_DB_APP: hello-pg-test

tasks:
  # https://fly.io/docs/postgres/managing/attach-detach/
  attach-hello-api: fly postgres attach {{.FLY_DB_APP}} --app hello-api-elixir
  db: fly pg connect -a {{.FLY_DB_APP}}
  # https://fly.io/docs/postgres/getting-started/create-pg-cluster/
  mk-cluster: fly postgres create --autostart --name {{.FLY_DB_APP}}
